### ISSUE TITLE
Horizontal navigation bar problem

### ISSUE THREAD

**Issue by syslao** [codevise/pageflow-progress-navigation-bar#25]
Hi! After installation I have only one option available "Progress navigation bar (vertical)", how to enable a horizontal position? I cleared tmp/cache/assets/  but without result

rails 4.2.7
ruby 2.3.1
pageflow 0.11.3

**Comment by syslao** [comment]
It seems that I solved the problem myself. In config/initializers/pageflow.rb i added
config.widget_types.register(Pageflow::ProgressNavigationBar.horizontal_widget_type)

**Comment by tf** [comment]
Yes. This was missing in the readme. I've just updated the example code (#26).
